services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations}'

    App\Normalizer\Base\NormalizerFactory:
        arguments: [!tagged app.normalizer]