services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations}'

    App\Normalizer\CategoryNormalizer:
        arguments: ['%kernel.project_dir%']

    App\Normalizer\CourseNormalizer:
        arguments: ['%kernel.project_dir%']

    App\Normalizer\LanguageNormalizer:
        arguments: ['%kernel.project_dir%']

    App\Normalizer\UserNormalizer:
        arguments: ['%kernel.project_dir%']

    App\Normalizer\Base\NormalizerFactory:
        arguments: [!tagged app.normalizer]